### ISSUE TITLE
Black screen on linux with SSAO 

### ISSUE THREAD

**Issue by orderorder** [shinyquagsire23/OpenJKDF2#111] opened 2022-10-10 18:46 UTC
Card: AMD Radeon R7 240
Drivers: Mesa 22.1.7

Enable SSAO => Black Screen
Enable Texture Filtering => Game with no textures (all in white)

Without these display options the game works.

**Comment by shinyquagsire23** [comment] 2022-10-10 23:52
Out of curiosity, does it work with https://maxthomas.dev/openjkdf2/ or is it the same issue? I added some legacy GPU support for WebGL since it didn't support `GL_ARB_texture_gather` so I'm surprised it would have trouble.

**Comment by orderorder** [comment] 2022-10-11 10:02
Yes, it works with https://maxthomas.dev/openjkdf2/ with all display options marked

![Capture](https://user-images.githubusercontent.com/7293829/195057722-49334707-2cff-4422-b953-e1ee5007140e.png)

I would like to take this opportunity to ask you a few questions: 

-Is there a DISCORD group about this project to ask you questions? 

-Is it possible to play the video game from start to finish or is there something left to implement? 

-Will it continue to depend in the future on the original executable? 

Thank you for your time

**Comment by shinyquagsire23** [comment] 2022-10-11 17:16
Interesting, one thing to check: in `~/.local/share/openjkdf2/resources`, is there a shaders folder? If there's files in there, delete them, I moved shaders into the executable because it made updating difficult.

If there are no shaders, I'll see if I can do more checks on OpenGL and select versions at runtime.

I don't have an official Discord per-se, you can DM me at shinyquagsire23#0819, or I hang out in the #jkreverseengineering channel in this one (the other channels can get a bit uhhhh, edgy. I have them muted and thankfully the admins are pretty good at keeping the topics moderated lol) https://discord.gg/2tRHCNdd

OpenJKDF2 is playable from start to finish for JKDF2, however MoTS is currently in-progrees but I'm anticipating full playability in 2~3 months as I integrate all the changes.

OpenJKDF2 no longer relies on the original executable. I have some specific build configurations I occasionally use for tracking project completion and regression testing that will read JK.EXE, but they're not defaults.

**Comment by orderorder** [comment] 2022-10-11 19:00
i dont have the folder .local/share/openjkdf2. But if I delete in the game the folder "shaders" inside  "Resource" then it works well

**Comment by shinyquagsire23** [comment] 2022-10-11 19:03
oh perfect, then I'll go ahead and close the issue.

**Closed by shinyquagsire23** 2022-10-11 19:03 UTC
Labels: bug
